name: Deploy FollowMe App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify repository contents
        run: |
          ls -la
          echo "Contents of the repository:"
          find . -type f -not -path "./.git/*" -not -path "./node_modules/*"

      - name: Setup Node.js (without npm cache)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # Removido o cache para evitar problemas com lock file

      - name: Create package-lock.json if missing
        id: create-lock
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating new package-lock.json..."
            npm install --package-lock-only
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add package-lock.json
            git commit -m "Auto-generated package-lock.json" || echo "No changes to commit"
            # Não fazemos push aqui para evitar loops infinitos
            echo "lock_file_created=true" >> $GITHUB_OUTPUT
          else
            echo "package-lock.json already exists"
            echo "lock_file_created=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          npm ci --no-audit --ignore-scripts
          npm install @trpc/server @trpc/client @trpc/react-query @tanstack/react-query zod superjson
          npm install --save-dev @types/node @types/react @types/react-dom

      - name: Build project
        run: npm run build

      - name: Validate build output
        run: |
          [ -d .next/static ] || (echo "❌ Build failed - no static files generated" && exit 1)

      - name: Deploy to Azure via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: './.next,public,package.json,package-lock.json,next.config.js'
          target: '/var/www/FollowMe-app'
          strip_components: 1

      - name: SSH - Setup and Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/FollowMe-app
            npm ci --production --no-audit
            npm install pm2 -g
            pm2 delete FollowMe-app || true
            pm2 start npm --name "FollowMe-app" -- start
            pm2 save
            pm2 startup
