name: Deploy FollowMe App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --package-lock-only
          npm ci --no-audit
          npm install @trpc/server @trpc/client @trpc/react-query @tanstack/react-query zod superjson
          npm install --save-dev @types/node @types/react @types/react-dom typescript

      - name: Build project
        run: |
          # Verifica estrutura de arquivos
          [ -f server/trpc.ts ] || (echo "❌ server/trpc.ts não encontrado" && exit 1)
          [ -f server/routers/index.ts ] || (echo "❌ server/routers/index.ts não encontrado" && exit 1)
          [ -f utils/trpc.ts ] || (echo "❌ utils/trpc.ts não encontrado" && exit 1)
          
          npm run build

      - name: Deploy to Azure via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: './.next,public,package.json,package-lock.json,next.config.js,next-env.d.ts,tsconfig.json,server,utils'
          target: '/var/www/FollowMe-app'
          strip_components: 1

      - name: SSH - Setup and Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/FollowMe-app
            npm ci --production
            npm install pm2 -g
            pm2 delete FollowMe-app || true
            pm2 start npm --name "FollowMe-app" -- start
            pm2 save
            pm2 startup
