name: Deploy Task Manager App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --no-audit

      - name: Build project
        run: npm run build

      - name: Deploy to Azure via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: 'app/*,.next,public,package.json,package-lock.json,tsconfig.json,next.config.js'
          target: '/var/www/FollowMe'
          strip_components: 1

      - name: SSH - Setup and Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/task-manager-app
            npm ci --production
            npm install pm2 -g
            pm2 delete FollowMe || true
            pm2 start npm --name "FollowMe" -- start
            pm2 save
            pm2 startup
