name: Deploy FollowMe App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify project files
        run: |
          if [ ! -f package.json ]; then
            echo "❌ package.json not found!"
            exit 1
          fi
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          [ -d .next ] || (echo "❌ Build failed - no .next directory" && exit 1)

      - name: Deploy to Azure via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: '.[!.]*'  # Copies all files except hidden ones
          target: '/var/www/FollowMe'
          strip_components: 0
          overwrite: true

      - name: SSH - Setup and Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/FollowMe
            npm ci --production --no-audit
            npm install pm2 -g
            pm2 delete FollowMe || true
            pm2 start npm --name "FollowMe" -- start
            pm2 save
            pm2 startup
