name: Deploy to Azure Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install trpc react-query
        run: npm install @trpc/react-query superjson

      - name: Build project
        run: npm run build

      - name: Deploy via SCP to Azure Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: './*'
          target: '/var/www/FollowMe-app'

      - name: SSH - Install dependencies and restart app with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/FollowMe-app
            npm install
            npm run build
            npx pm2 restart ecosystem.config.js || npx pm2 start ecosystem.config.js
