name: Deploy FollowMe App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: '/var/www/FollowMe-app'

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para garantir o histórico completo

      # 2. Verificação do package.json
      - name: Verify project structure
        run: |
          if [ ! -f package.json ]; then
            echo "❌ ERRO: package.json não encontrado!"
            exit 1
          fi
          
          # Gera o package-lock.json se não existir
          if [ ! -f package-lock.json ]; then
            echo "⚠ AVISO: package-lock.json não encontrado, gerando novo..."
            npm install --package-lock-only
            git add package-lock.json || true
          fi

      # 3. Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Habilita cache de dependências

      # 4. Instalação de dependências
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      # 5. Build do projeto
      - name: Build project
        run: npm run build

      # 6. Verificação do build
      - name: Verify build output
        run: |
          [ -d .next ] || (echo "❌ ERRO: Build falhou - diretório .next não encontrado" && exit 1)

      # 7. Deploy via SCP
      - name: Deploy to Azure
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: '.[!.]*'  # Copia todos arquivos não ocultos
          target: ${{ env.APP_DIR }}
          overwrite: true
          strip_components: 0

      # 8. Configuração no servidor
      - name: Setup on Azure
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.APP_DIR }}
            
            # Instalação segura de dependências
            if [ -f package-lock.json ]; then
              npm ci --production --no-audit
            else
              echo "⚠ AVISO: package-lock.json não encontrado no servidor, usando npm install"
              npm install --production --no-audit
            fi
            
            # Gerenciamento do PM2
            npm install pm2 -g
            pm2 delete FollowMe || true
            pm2 start npm --name "FollowMe" -- start
            pm2 save
            pm2 startup
